[package]
name = "time-blocking-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
simple_db = { path = "./brudb/simpledb" }
dialoguer = "0.10.2"
cron = "0.9.0"
notify-rust = "4.0.0"
chrono = "0.4"